name: anadodik
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - Jinja2
      # Linters:
      - flake8
      - flake8-copyright
      - mypy
      - black
      - isort
      # Testing:
      - pytest
      - pytest-cov
